FROM python:3.8

ENV PYTHONUNBUFFERED 1

WORKDIR /app

RUN apt update

COPY users/requirements.txt /requirements.txt
RUN pip install --upgrade pip
RUN pip install -r /requirements.txt

ENV PYTHONPATH /app

